[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }
serde_json = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-net = { version = "0.6", features = ["websocket"] }
gloo-timers = "0.3"
wasm-bindgen-futures = "0.4"
futures-util = "0.3"
web-sys = { version = "0.3", features = ["Window", "Location", "console"] }

[features]
server = ["api/server"]
